In [8]:
! pip install kaggle

Requirement already satisfied: kaggle in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.2.4)
Requirement already satisfied: bleach in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (1.2.3)
Requirement already satisfied: python-slugify in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (9.1.2)
Requirement already satisfied: requests in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (4.68.3)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupytext->kaggle) (5.11.0)
Requirement already satisfied: pyyaml in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat->jupytext->kaggle) (2.22.1)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nbformat->jupytext->kaggle) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: six>=1.5 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kaggle) (3.15)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: colorama in C:\Users\Acer\AppData\Local\Programs\Python\Python314\Lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
! kaggle datasets download -d nelgiriyewithana/credit-card-fraud-detection-dataset-2023

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.2.4), please consider upgrading to the latest version (2.2.5)
Dataset URL: https://www.kaggle.com/datasets/nelgiriyewithana/credit-card-fraud-detection-dataset-2023
License(s): other
Downloading credit-card-fraud-detection-dataset-2023.zip to d:\Machine-Learning\fraud detection

  0%|          | 0.00/143M [00:00<?, ?B/s]
  1%|          | 1.00M/143M [00:00<02:11, 1.13MB/s]
  1%|▏         | 2.00M/143M [00:01<01:13, 2.02MB/s]
  2%|▏         | 3.00M/143M [00:01<00:49, 2.95MB/s]
  3%|▎         | 4.00M/143M [00:01<00:38, 3.79MB/s]
  3%|▎         | 5.00M/143M [00:01<00:34, 4.15MB/s]
  4%|▍         | 6.00M/143M [00:01<00:32, 4.41MB/s]
  5%|▍         | 7.00M/143M [00:02<00:29, 4.77MB/s]
  6%|▌         | 8.00M/143M [00:02<00:29, 4.74MB/s]
  6%|▋         | 9.00M/143M [00:02<00:28, 4.98MB/s]
  7%|▋         | 10.0M/143M [00:02<00:27, 5.00MB/s]
  8%|▊         | 11.0M/143M [00:02<00:25, 5.40MB/s]
  8%|▊         | 12.0M/143M [00:03<00:23, 5.79MB/s]
  9%|▉         | 13.0M/143M [00:03<00:22, 6.18MB/s]
 10%|▉         | 14.0M/143M [00:03<00:22, 5.89MB/s]
 10%|█         | 15.0M/143M [00:03<00:21, 6.20MB/s]
 11%|█         | 16.0M/143M [00:03<00:21, 6.22MB/s]
 12%|█▏        | 17.0M/143M [00:03<00:21, 6.27MB/s]
 13%|█▎        | 18.0M/143M [00:04<00:22, 5.80MB/s]
 13%|█▎        | 19.0M/143M [00:04<00:21, 6.06MB/s]
 14%|█▍        | 20.0M/143M [00:04<00:23, 5.55MB/s]
 15%|█▍        | 21.0M/143M [00:04<00:21, 5.88MB/s]
 15%|█▌        | 22.0M/143M [00:04<00:20, 6.12MB/s]
 16%|█▌        | 23.0M/143M [00:04<00:19, 6.34MB/s]
 17%|█▋        | 24.0M/143M [00:05<00:19, 6.55MB/s]
 17%|█▋        | 25.0M/143M [00:05<00:18, 6.68MB/s]
 18%|█▊        | 26.0M/143M [00:05<00:18, 6.72MB/s]
 19%|█▉        | 27.0M/143M [00:05<00:17, 6.82MB/s]
 20%|█▉        | 28.0M/143M [00:05<00:24, 4.95MB/s]
 20%|██        | 29.0M/143M [00:06<00:25, 4.77MB/s]
 21%|██        | 30.0M/143M [00:06<00:22, 5.20MB/s]
 22%|██▏       | 31.0M/143M [00:06<00:23, 5.06MB/s]
 22%|██▏       | 32.0M/143M [00:06<00:21, 5.52MB/s]
 23%|██▎       | 33.0M/143M [00:06<00:20, 5.62MB/s]
 24%|██▍       | 34.0M/143M [00:06<00:19, 5.96MB/s]
 24%|██▍       | 35.0M/143M [00:07<00:17, 6.30MB/s]
 25%|██▌       | 36.0M/143M [00:07<00:17, 6.41MB/s]
 26%|██▌       | 37.0M/143M [00:07<00:17, 6.46MB/s]
 27%|██▋       | 38.0M/143M [00:07<00:16, 6.55MB/s]
 27%|██▋       | 39.0M/143M [00:07<00:17, 6.22MB/s]
 28%|██▊       | 40.0M/143M [00:07<00:17, 6.19MB/s]
 29%|██▊       | 41.0M/143M [00:08<00:16, 6.33MB/s]
 29%|██▉       | 42.0M/143M [00:08<00:16, 6.50MB/s]
 30%|███       | 43.0M/143M [00:08<00:15, 6.83MB/s]
 31%|███       | 44.0M/143M [00:08<00:14, 6.94MB/s]
 31%|███▏      | 45.0M/143M [00:08<00:14, 6.90MB/s]
 32%|███▏      | 46.0M/143M [00:08<00:15, 6.64MB/s]
 33%|███▎      | 47.0M/143M [00:08<00:14, 6.81MB/s]
 34%|███▎      | 48.0M/143M [00:09<00:14, 6.83MB/s]
 34%|███▍      | 49.0M/143M [00:09<00:14, 6.67MB/s]
 35%|███▍      | 50.0M/143M [00:09<00:14, 6.70MB/s]
 36%|███▌      | 51.0M/143M [00:09<00:14, 6.64MB/s]
 36%|███▋      | 52.0M/143M [00:09<00:15, 6.13MB/s]
 37%|███▋      | 53.0M/143M [00:09<00:14, 6.35MB/s]
 38%|███▊      | 54.0M/143M [00:10<00:15, 6.14MB/s]
 38%|███▊      | 55.0M/143M [00:10<00:14, 6.38MB/s]
 39%|███▉      | 56.0M/143M [00:10<00:13, 6.57MB/s]
 40%|███▉      | 57.0M/143M [00:10<00:13, 6.77MB/s]
 41%|████      | 58.0M/143M [00:10<00:15, 5.83MB/s]
 41%|████▏     | 59.0M/143M [00:10<00:14, 6.06MB/s]
 42%|████▏     | 60.0M/143M [00:11<00:20, 4.30MB/s]
 43%|████▎     | 61.0M/143M [00:11<00:17, 4.89MB/s]
 43%|████▎     | 62.0M/143M [00:11<00:15, 5.39MB/s]
 44%|████▍     | 63.0M/143M [00:11<00:14, 5.82MB/s]
 45%|████▍     | 64.0M/143M [00:12<00:14, 5.79MB/s]
 45%|████▌     | 65.0M/143M [00:12<00:13, 6.00MB/s]
 46%|████▌     | 66.0M/143M [00:12<00:12, 6.26MB/s]
 47%|████▋     | 67.0M/143M [00:12<00:12, 6.47MB/s]
 48%|████▊     | 68.0M/143M [00:12<00:12, 6.39MB/s]
 48%|████▊     | 69.0M/143M [00:12<00:11, 6.54MB/s]
 49%|████▉     | 70.0M/143M [00:12<00:11, 6.51MB/s]
 50%|████▉     | 71.0M/143M [00:13<00:11, 6.58MB/s]
 50%|█████     | 72.0M/143M [00:13<00:11, 6.69MB/s]
 51%|█████     | 73.0M/143M [00:13<00:10, 6.82MB/s]
 52%|█████▏    | 74.0M/143M [00:13<00:10, 6.78MB/s]
 52%|█████▏    | 75.0M/143M [00:13<00:11, 6.21MB/s]
 53%|█████▎    | 76.0M/143M [00:14<00:19, 3.63MB/s]
 55%|█████▍    | 78.0M/143M [00:14<00:12, 5.25MB/s]
 55%|█████▌    | 79.0M/143M [00:14<00:11, 5.60MB/s]
 56%|█████▌    | 80.0M/143M [00:14<00:11, 5.85MB/s]
 57%|█████▋    | 81.0M/143M [00:14<00:10, 6.18MB/s]
 57%|█████▋    | 82.0M/143M [00:15<00:10, 6.33MB/s]
 58%|█████▊    | 83.0M/143M [00:15<00:09, 6.61MB/s]
 59%|█████▊    | 84.0M/143M [00:15<00:10, 6.13MB/s]
 59%|█████▉    | 85.0M/143M [00:15<00:09, 6.09MB/s]
 60%|██████    | 86.0M/143M [00:15<00:09, 6.36MB/s]
 61%|██████    | 87.0M/143M [00:17<00:32, 1.81MB/s]
 62%|██████▏   | 88.0M/143M [00:19<01:00, 947kB/s]
 62%|██████▏   | 89.0M/143M [00:20<00:46, 1.21MB/s]
 63%|██████▎   | 90.0M/143M [00:22<01:14, 743kB/s]
 64%|██████▎   | 91.0M/143M [00:23<01:04, 839kB/s]
 64%|██████▍   | 92.0M/143M [00:26<01:26, 618kB/s]
 66%|██████▌   | 94.0M/143M [00:26<00:47, 1.08MB/s]
 66%|██████▋   | 95.0M/143M [00:26<00:39, 1.28MB/s]
 67%|██████▋   | 96.0M/143M [00:27<00:30, 1.59MB/s]
 68%|██████▊   | 97.0M/143M [00:27<00:24, 1.96MB/s]
 69%|██████▊   | 98.0M/143M [00:27<00:20, 2.30MB/s]
 69%|██████▉   | 99.0M/143M [00:27<00:16, 2.75MB/s]
 70%|██████▉   | 100M/143M [00:27<00:14, 3.12MB/s]
 71%|███████   | 101M/143M [00:28<00:11, 3.71MB/s]
 71%|███████▏  | 102M/143M [00:28<00:10, 4.20MB/s]
 72%|███████▏  | 103M/143M [00:28<00:09, 4.34MB/s]
 73%|███████▎  | 104M/143M [00:28<00:08, 4.84MB/s]
 73%|███████▎  | 105M/143M [00:28<00:07, 5.22MB/s]
 74%|███████▍  | 106M/143M [00:29<00:06, 5.62MB/s]
 75%|███████▍  | 107M/143M [00:29<00:06, 5.94MB/s]
 76%|███████▌  | 108M/143M [00:29<00:06, 5.78MB/s]
 76%|███████▌  | 109M/143M [00:29<00:05, 6.11MB/s]
 77%|███████▋  | 110M/143M [00:29<00:05, 5.86MB/s]
 78%|███████▊  | 111M/143M [00:29<00:05, 6.18MB/s]
 78%|███████▊  | 112M/143M [00:30<00:05, 6.35MB/s]
 79%|███████▉  | 113M/143M [00:30<00:04, 6.62MB/s]
 80%|███████▉  | 114M/143M [00:30<00:04, 6.68MB/s]
 80%|████████  | 115M/143M [00:30<00:05, 5.55MB/s]
 81%|████████  | 116M/143M [00:30<00:04, 5.85MB/s]
 82%|████████▏ | 117M/143M [00:30<00:04, 6.02MB/s]
 83%|████████▎ | 118M/143M [00:31<00:04, 5.76MB/s]
 83%|████████▎ | 119M/143M [00:31<00:04, 6.13MB/s]
 84%|████████▍ | 120M/143M [00:31<00:03, 6.40MB/s]
 85%|████████▍ | 121M/143M [00:31<00:03, 6.41MB/s]
 85%|████████▌ | 122M/143M [00:31<00:03, 6.55MB/s]
 86%|████████▌ | 123M/143M [00:31<00:03, 6.56MB/s]
 87%|████████▋ | 124M/143M [00:32<00:03, 5.28MB/s]
 87%|████████▋ | 125M/143M [00:32<00:03, 5.06MB/s]
 88%|████████▊ | 126M/143M [00:32<00:03, 5.50MB/s]
 89%|████████▉ | 127M/143M [00:32<00:02, 5.87MB/s]
 90%|████████▉ | 128M/143M [00:32<00:02, 5.84MB/s]
 90%|█████████ | 129M/143M [00:32<00:02, 6.21MB/s]
 91%|█████████ | 130M/143M [00:33<00:02, 6.50MB/s]
 92%|█████████▏| 131M/143M [00:33<00:01, 6.61MB/s]
 92%|█████████▏| 132M/143M [00:33<00:01, 6.77MB/s]
 93%|█████████▎| 133M/143M [00:33<00:01, 6.82MB/s]
 94%|█████████▎| 134M/143M [00:33<00:01, 6.79MB/s]
 94%|█████████▍| 135M/143M [00:33<00:01, 6.66MB/s]
 95%|█████████▌| 136M/143M [00:34<00:01, 6.80MB/s]
 96%|█████████▌| 137M/143M [00:34<00:00, 6.81MB/s]
 96%|█████████▋| 138M/143M [00:34<00:00, 6.91MB/s]
 97%|█████████▋| 139M/143M [00:34<00:00, 6.86MB/s]
 98%|█████████▊| 140M/143M [00:34<00:00, 6.39MB/s]
 99%|█████████▊| 141M/143M [00:34<00:00, 6.34MB/s]
 99%|█████████▉| 142M/143M [00:35<00:00, 6.51MB/s]
100%|█████████▉| 143M/143M [00:35<00:00, 6.74MB/s]
100%|██████████| 143M/143M [00:35<00:00, 4.26MB/s]

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.read_csv('credit-card-fraud-detection-dataset-2023.zip')

In [47]:
df.shape

(568630, 31)

In [48]:
df.head(15)

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0
5,5,0.025302,-0.140514,1.191138,-0.707979,0.430490,0.458973,0.611050,-0.092629,0.180811,...,-0.187739,-0.538518,-0.050465,-0.631553,-0.456480,0.252670,0.066681,0.095812,6901.49,0
6,6,1.016482,-0.397181,0.497868,-0.144463,0.331022,0.629243,0.431262,-0.134007,0.796159,...,-0.171137,-0.287017,-0.178197,-1.297597,1.182503,-0.604228,-0.198163,-0.087619,18954.45,0
7,7,-0.051306,-0.007194,1.139941,-0.877880,0.684668,0.714326,0.892615,-0.908409,0.901938,...,0.620676,-0.920426,0.034660,-1.091527,-0.742075,-0.104863,-1.382522,-2.748268,12298.23,0
8,8,-0.130680,-0.349547,0.425786,-0.760444,1.702777,2.324816,0.568968,0.049100,0.273118,...,-0.132787,-0.284700,-0.227779,2.248754,0.534846,-0.929738,-0.224385,0.243790,22052.90,0
9,9,0.058419,-0.093507,1.117270,-0.735172,0.466111,0.332371,0.683425,-0.136674,0.096409,...,-0.203634,-0.601581,-0.145082,-0.654783,-0.196621,0.226818,0.057119,0.100629,210.35,0
10,10,1.206014,-0.883519,1.021299,-1.410047,-0.341591,0.101491,0.036318,-0.141480,-0.348832,...,-0.106932,0.252151,0.004350,1.065933,0.330100,-0.289691,-0.188490,-0.060815,4741.71,0
11,11,0.409314,-0.245063,0.152566,-0.671316,1.874091,2.139539,0.608736,-0.026862,0.185819,...,-0.083222,0.180021,-0.014540,2.212670,-1.280261,-1.216546,-0.188929,-0.231608,14574.34,0
12,12,1.033525,-0.901634,0.676980,-1.319313,-0.216000,0.024725,0.222965,-0.203210,-0.501905,...,-0.197417,-0.472722,0.062430,0.832732,0.180102,-0.853823,-0.207514,0.002436,21696.89,0
13,13,0.886031,-0.349039,0.960931,0.333001,0.186379,0.664916,0.400542,-0.126042,0.366589,...,-0.118027,0.025738,-0.095727,0.240107,0.833120,0.248660,-0.213190,-0.048630,12157.97,0
14,14,-0.571544,-0.559877,1.609161,0.045297,0.201712,0.916651,0.298916,-0.549311,1.003897,...,0.336079,0.164591,1.068878,0.091185,-0.456405,-0.549904,-0.419742,-0.173067,508.29,0

In [49]:
df.isnull().sum()

id        0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 568630 entries, 0 to 568629
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      568630 non-null  int64
 1   V1      568630 non-null  float64
 2   V2      568630 non-null  float64
 3   V3      568630 non-null  float64
 4   V4      568630 non-null  float64
 5   V5      568630 non-null  float64
 6   V6      568630 non-null  float64
 7   V7      568630 non-null  float64
 8   V8      568630 non-null  float64
 9   V9      568630 non-null  float64
 10  V10     568630 non-null  float64
 11  V11     568630 non-null  float64
 12  V12     568630 non-null  float64
 13  V13     568630 non-null  float64
 14  V14     568630 non-null  float64
 15  V15     568630 non-null  float64
 16  V16     568630 non-null  float64
 17  V17     568630 non-null  float64
 18  V18     568630 non-null  float64
 19  V19     568630 non-null  float64
 20  V20     568630 non-null  float64
 21  V21     568630 non-null  float64
 22  V22     568630 non-null  float64
 23  V23     568630 non-null  float64
 24  V24     568630 non-null  float64
 25  V25     568630 non-null  float64
 26  V26     568630 non-null  float64
 27  V27     568630 non-null  float64
 28  V28     568630 non-null  float64
 29  Amount  568630 non-null  float64
 30  Class   568630 non-null  int64
dtypes: float64(29), int64(2)
memory usage: 134.5 MB

In [51]:
df.describe()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,568630.000000,5.686300e+05,5.686300e+05,5.686300e+05,568630.000000,5.686300e+05,5.686300e+05,568630.000000,5.686300e+05,568630.000000,...,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,568630.000000,568630.0
mean,284314.500000,-5.118237e-17,-5.118237e-17,1.023647e-16,0.000000,2.559118e-17,2.559118e-17,0.000000,1.279559e-17,0.000000,...,1.279559e-17,1.599449e-18,5.598072e-18,-2.559118e-17,-4.478457e-17,-6.397796e-18,-2.559118e-17,3.198898e-17,12041.957635,0.5
std,164149.486122,1.000001e+00,1.000001e+00,1.000001e+00,1.000001,1.000001e+00,1.000001e+00,1.000001,1.000001e+00,1.000001,...,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,6919.644449,0.5
min,0.000000,-3.495584e+00,-4.996657e+01,-3.183760e+00,-4.951222,-9.952786e+00,-2.111111e+01,-4.351839,-1.075634e+01,-3.751919,...,-1.938252e+01,-7.734798e+00,-3.029545e+01,-4.067968e+00,-1.361263e+01,-8.226969e+00,-1.049863e+01,-3.903524e+01,50.010000,0.0
25%,142157.250000,-5.652859e-01,-4.866777e-01,-6.492987e-01,-0.656020,-2.934955e-01,-4.458712e-01,-0.283533,-1.922572e-01,-0.568745,...,-1.664408e-01,-4.904892e-01,-2.376289e-01,-6.515801e-01,-5.541485e-01,-6.318948e-01,-3.049607e-01,-2.318783e-01,6054.892500,0.0
50%,284314.500000,-9.363846e-02,-1.358939e-01,3.528579e-04,-0.073762,8.108788e-02,7.871758e-02,0.233366,-1.145242e-01,0.092526,...,-3.743065e-02,-2.732881e-02,-5.968903e-02,1.590123e-02,-8.193162e-03,-1.189208e-02,-1.729111e-01,-1.392973e-02,12030.150000,0.5
75%,426471.750000,8.326582e-01,3.435552e-01,6.285380e-01,0.707005,4.397368e-01,4.977881e-01,0.525955,4.729905e-02,0.559262,...,1.479787e-01,4.638817e-01,1.557153e-01,7.007374e-01,5.500147e-01,6.728879e-01,3.340230e-01,4.095903e-01,18036.330000,1.0
max,568629.000000,2.229046e+00,4.361865e+00,1.412583e+01,3.201536,4.271689e+01,2.616840e+01,217.873038,5.958040e+00,20.270062,...,8.087080e+00,1.263251e+01,3.170763e+01,1.296564e+01,1.462151e+01,5.623285e+00,1.132311e+02,7.725594e+01,24039.930000,1.0

In [52]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop('Class', axis=1), df['Class'], test_size=0.2, random_state=42)

In [53]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(454904, 30) (113726, 30) (454904,) (113726,)

In [54]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, ...)

In [55]:
y_pred = model.predict(x_test)

print("Prediction:", y_pred)

Prediction: [1 1 0 ... 1 1 0]

In [57]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
    )

print("Accuracy :", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred, zero_division=0), 4))
print("Recall   :", round(recall_score(y_test, y_pred, zero_division=0), 4))
print("F1 Score :", round(f1_score(y_test, y_pred, zero_division=0), 4))

Accuracy : 0.9998
Precision: 0.9999
Recall   : 0.9997
F1 Score : 0.9998

In [60]:
actual = y_test.iloc[3]

prediction = model.predict(x_test.iloc[[3]])[0]

print("Actual class:", actual)
print("Predicted class:", prediction)

if actual == prediction:
    print("Prediction is correct")
else:
    print("Prediction is incorrect")

Actual class: 1
Predicted class: 1
Prediction is correct

In [61]:
import joblib

joblib.dump(model, "xgboost_fraud_model.pkl")

print("Model saved successfully!")

Model saved successfully!